a2lix_translation_form:
    locale_provider: default
    locales: '%kernel.enabled_locales%'
#    locales: [en, fr, es, tzo, zh]
    default_locale: en
    required_locales: [en]
    templating: "@A2lixTranslationForm/bootstrap_5_layout.html.twig"
