twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        repoUrl: https://github.com/survos-sites/easyadmin-translation-form-demo

when@test:
    twig:
        strict_variables: true
