<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250526151723 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE doc (key VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, line_count INT NOT NULL, PRIMARY KEY(key))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX line_count_index ON doc (line_count)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE doc_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, body TEXT DEFAULT NULL, character_count INT DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id VARCHAR DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_E7E09FD62C2AC5D3 ON doc_translation (translatable_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX doc_translation_unique_translation ON doc_translation (translatable_id, locale)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, domain VARCHAR(255) NOT NULL, text_key VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE message_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT DEFAULT NULL, locale VARCHAR(5) NOT NULL, translatable_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D4161B962C2AC5D3 ON message_translation (translatable_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX message_translation_unique_translation ON message_translation (translatable_id, locale)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE doc_translation ADD CONSTRAINT FK_E7E09FD62C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES doc (key) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE message_translation ADD CONSTRAINT FK_D4161B962C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE doc_translation DROP CONSTRAINT FK_E7E09FD62C2AC5D3
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE message_translation DROP CONSTRAINT FK_D4161B962C2AC5D3
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE doc
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE doc_translation
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE message
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE message_translation
        SQL);
    }
}
